can:
  can_type: TCP
  host: localhost
  port: 8881
default_user:
  password: test
  username: test
http:
  listen_addr: :8080
lockout:
  enabled: true
  listen_addr: :5445
sqlite:
  dsn: ./main.db
time_series:
  directory: ./sensor_data
